amader_dokan/amader_dokan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include(('account.urls', 'app_name'), namespace='account')),
    path('', include(('store.urls', 'app_name'), namespace='store')),
    path('order/', include(('order.urls', 'app_name'), namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

amader_dokan/order/urls.py
from django.urls import path
from order import views

app_name = 'order'
urlpatterns = [
    path('add-to-cart/<int:pk>/', views.add_to_cart, name='add-to-cart'),
    path('cart-view/', views.cart_view, name='cart'),
    path('remove-item/<int:pk>/', views.remove_item_from_cart, name='remove-item'),
    path('increase-quentity/<int:pk>/', views.increase_cart, name='increase'),
    path('decrease-quentity/<int:pk>/', views.decrease_cart, name='decrease'),
]

amader_dokan/store/urls.py
from django.urls import path
from store import views

app_name = 'store'
urlpatterns = [
    path('', views.HomeListView.as_view(), name='index'),
    # path('product/<int:prod_id>/',
    #      views.product_details, name='product-details'),
    # path('product/<str:pk>/',
    #      views.ProductViewDetails.as_view(), name='product-details')
    path('product/<str:slug>/',
         views.ProductViewDetails.as_view(), name='product-details'),
    # path('category/<category>/', views.category_view, name='category-view')
]

amader_dokan/store/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=50, blank=False, null=False)
    image = models.ImageField(upload_to='category', blank=True, null=True)
    parent = models.ForeignKey(
        'self', related_name='children', on_delete=models.CASCADE, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ['-created']
        verbose_name_plural = 'Categories'


class Product(models.Model):
    name = models.CharField(max_length=250, blank=False, null=False)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='category')
    preview_des = models.CharField(
        max_length=255, verbose_name='Short Descriptions')
    description = models.TextField(max_length=1000, verbose_name='Description')
    image = models.ImageField(upload_to='product', blank=False, null=False)
    price = models.FloatField()
    old_price = models.FloatField(default=0.00, blank=True, null=True)
    is_stock = models.BooleanField(default=True)
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.name

    def get_product_url(self):
        return reverse('store:product-details', kwargs={'slug': self.slug})

    class Mete:
        ordering = ['-created']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super(Product, self).save(*args, **kwargs)


class ProductImages(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    images = models.FileField(upload_to='product_gallery')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return str(self.product.name)


class VariationManager(models.Manager):
    def sizes(self):
        return super(VariationManager, self).filter(variation='size')

    def colors(self):
        return super(VariationManager, self).filter(variation='color')


VARIATIONS_TYPE = (
    ('size', 'size'),
    ('color', 'color'),
)


class VariationValue(models.Model):
    variation = models.CharField(max_length=100, choices=VARIATIONS_TYPE)
    name = models.CharField(max_length=50)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)

    objects = VariationManager()

    def __str__(self):
        return self.name

amader_dokan/templates/home/index.html
{% extends 'base.html' %}
{% load cart_product %}
<!-- {% load static %} -->

{% block homeStatic %}
<link rel="stylesheet" href="{% static 'home/style.css' %}">
{% endblock %}

{% block title %}{{ view.build_page_title }}{% endblock %}

{% block index %}
<div class="container" style="background-color: aqua; margin-bottom: 50px;">
    <h1>Cart</h1>
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">image</th>
                    <th scope="col">Nmae</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Price</th>
                </tr>
            </thead>
            <tbody>
                {% if request.user.is_authenticated %}
                {% if request.user|cart_view %}
                {% for cart in request.user|cart_view %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td><img style="height: 50px; width: 50px;" src="{{ cart.item.image.url }}" alt=""></td>
                    <td>{{ cart.item.name }}</td>
                    <td>{{ cart.quantity }} X {{ cart.item.price }}</td>
                    <td>{{ cart.get_total }}</td>
                </tr>
                {% endfor %}
                {% endif %}
                {% endif %}
            </tbody>
            <tfoot>
                <tr>
                    <th></th>
                    <th></th>
                    <th><a href="{% url 'order:cart' %}" class="btn btn-primary">View Cart</a></th>
                    {% if request.user.is_authenticated %}
                    <th>Total Price</th>
                    <th>BDT {{request.user|cart_total_price}}</th>
                    {% else %}
                    <th>BDT 0.00</th>
                    {% endif %}
                </tr>
            </tfoot>
        </table>
    </div>
</div>
<div class="container">
    <div class="row">
        {% for product in products %}
        <div class="col">
            <div class="card" style="width: 18rem;">
                <img src="{{ product.image.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <h3><samp style="font-size: 1.7rem;">৳</samp> {{ product.price }}</h3>
                    {% if product.old_price %}
                    <h4 style="opacity: 0.5; text-decoration: solid line-through;"><samp
                            style="font-size: 1.3rem;">৳</samp> {{ product.price }}</h4>
                    {% endif %}
                    <p class="card-text">{{ product.preview_des }}</p>
                    <a href="{{ product.get_product_url }}" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

amader_dokan/templates/home/product.html
{% extends 'base.html' %}
{% block index %}

<div class="container">
    <h1><a href="{% url 'store:index' %}">Home</a></h1>
</div>

<div class="container">
    <div class="row">
        {% for photos in product_images %}
        <div class="col">
            <div class="image">
                <img style="height: 100px; width: 100px;" src="{{ photos.images.url }}" alt="">
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<div class="container">
    <div class="card mb-3">
        <img src="{{ item.image.url }}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">{{ item.name }}</h5>
            <h3><samp style="font-size: 1.7rem;">৳</samp> {{ item.price }}</h3>
            {% if item.old_price %}
            <h4 style="opacity: 0.5; text-decoration: solid line-through;"><samp style="font-size: 1.3rem;">
                    ৳</samp> {{item.price }}</h4>
            {% endif %}
            <p class="card-text">{{ item.description }}</p>



            <form method="post" action="{% url 'order:add-to-cart' pk=item.pk %}">
                {% csrf_token %}
                {% if item.variationvalue_set.sizes %}
                <div class="col">
                    <label for="size">Size</label>
                    <select class="form-select" name="size" id="size">
                        <option value="#" selected="selected">Select a size</option>
                        {% for item_variation in item.variationvalue_set.sizes %}
                        <option name='size' value="{{item_variation.name}}">{{item_variation.name}}</option>
                        {% endfor %}
                    </select>
                </div>
                {% endif %}
                <br>
                <br>
                {% if item.variationvalue_set.colors %}
                <div class="col">
                    <label for="color">Colors:</label>
                    <select name="color" id="size" class="form-control">
                        <option value="#" selected="selected">Select a color</option>
                        {% for item_variation in item.variationvalue_set.colors %}
                        <option name='color' value="{{item_variation.name}}">{{item_variation.name}}</option>
                        {% endfor %}
                    </select>
                </div>
                {% endif %}
                <br>
                <div class="form-outline">
                    <label class="form-label" for="typeNumber">Quantity</label>
                    <input type="number" id="typeNumber" class="form-control" name="quantity" value="1" min="1" max="5">
                </div>
                <br>
                <button type="submit" class="btn btn-primary">Add To Cart</button>
            </form>
            <p class="card-text"><small class="text-muted">{{ item.created }}</small></p>
        </div>
    </div>
</div>
<div class="container similar-product">
    <h1>Similar Product</h1>
    <div class="row">
        {% for it in similar_item %}
        {% if item.id != it.id %}
        <div class="col">
            <div class="card" style="width: 18rem;">
                <img src="{{ it.image.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ it.name }}</h5>
                    <h3><samp style="font-size: 1.7rem;">৳</samp> {{ it.price }}</h3>
                    {% if it.old_price %}
                    <h4 style="opacity: 0.5; text-decoration: solid line-through;"><samp
                            style="font-size: 1.3rem;">৳</samp> {{ it.price }}</h4>
                    {% endif %}
                    <p class="card-text">{{ it.preview_des }}</p>
                    <a href="{{ it.get_product_url }}" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>


    {% endblock %}