amader_dokan/amader_dokan/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include(('account.urls', 'app_name'), namespace='account')),
    path('', include(('store.urls', 'app_name'), namespace='store')),
    path('order/', include(('order.urls', 'app_name'), namespace='order')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

amader_dokan/order/urls.py
from django.urls import path
from order import views

app_name = 'order'
urlpatterns = [
    path('add-to-cart/<int:pk>/', views.add_to_cart, name='add-to-cart'),
    path('cart-view/', views.cart_view, name='cart'),
    path('remove-item/<int:pk>/', views.remove_item_from_cart, name='remove-item'),
    path('increase-quentity/<int:pk>/', views.increase_cart, name='increase'),
    path('decrease-quentity/<int:pk>/', views.decrease_cart, name='decrease'),
]

amader_dokan/store/urls.py
from django.urls import path
from store import views

app_name = 'store'
urlpatterns = [
    path('', views.HomeListView.as_view(), name='index'),
    # path('product/<int:prod_id>/',
    #      views.product_details, name='product-details'),
    # path('product/<str:pk>/',
    #      views.ProductViewDetails.as_view(), name='product-details')
    path('product/<str:slug>/',
         views.ProductViewDetails.as_view(), name='product-details'),
    # path('category/<category>/', views.category_view, name='category-view')
]

amader_dokan/order/models.py
from django.db import models
from django.contrib.auth.models import User
from store.models import Product, VariationValue


class Cart(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='cart')
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    size = models.CharField(max_length=100, blank=True, null=True)
    color = models.CharField(max_length=100, blank=True, null=True)
    purchased = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.quantity} X {self.item}"

    def get_total(self):
        total = self.item.price * self.quantity
        float_total = format(total, '0.2f')
        return float_total

    def variation_single_price(self):
        sizes = VariationValue.objects.filter(
            variation='size', product=self.item)
        colors = VariationValue.objects.filter(
            variation='color', product=self.item)
        for size in sizes:
            if colors.exists():
                for color in colors:
                    if color.name == self.color:
                        c_price = color.price
                if size.name == self.size:
                    total = size.price + c_price
                    net_total = total
                    float_total = format(net_total, '0.2f')
                    return float_total
            else:
                if size.name == self.size:
                    total = size.price
                    float_total = format(total, '0.2f')
                    return float_total

    def variation_total(self):
        sizes = VariationValue.objects.filter(
            variation='size', product=self.item)
        colors = VariationValue.objects.filter(
            variation='color', product=self.item)
        for size in sizes:
            if colors.exists():
                for color in colors:
                    if color.name == self.color:
                        c_price = color.price
                        color_quantity_price = c_price * self.quantity
                if size.name == self.size:
                    total = size.price * self.quantity
                    net_total = total + color_quantity_price
                    float_total = format(net_total, '0.2f')
                    return float_total
            else:
                if size.name == self.size:
                    total = size.price * self.quantity
                    float_total = format(total, '0.2f')
                    return float_total


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    orderitems = models.ManyToManyField(Cart)
    ordered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    paymentId = models.CharField(max_length=255, blank=True, null=True)
    orderId = models.CharField(max_length=255, blank=True, null=True)

    # def get_totals(self):
    #     total = 0
    #     for order_item in self.orderitems.all():
    #         total += float(order_item.get_total())
    #     return total

    def get_total_price(self):
        total_price = 0
        for item_price in self.orderitems.all():
            if item_price.variation_total():
                total_price += float(item_price.variation_total())
            elif item_price.variation_single_price():
                total_price += float(item_price.variation_single_price())
            else:
                total_price += float(item_price.get_total())
        return total_price

    def get_quantity(self):
        total_quantity = 0
        for order_items in self.orderitems.all():
            total_quantity += int(order_items.quantity)
        return total_quantity

amader_dokan/order/views.py
from django.shortcuts import get_object_or_404, render, redirect
from store.models import Product
from order.models import Cart, Order
from coupon.forms import CouponCodeForm
from coupon.models import Coupon
from django.utils import timezone
# Create your views here.


# function base views
def add_to_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_item = Cart.objects.get_or_create(
        item=item, user=request.user, purchased=False)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        size = request.POST.get('size')
        color = request.POST.get('color')
        quantity = request.POST.get('quantity')
        if order.orderitems.filter(item=item).exists():
            if quantity:
                order_item[0].quantity += int(quantity)
            else:
                order_item[0].quantity += 1
            order_item[0].size = size
            order_item[0].color = color
            order_item[0].save()
            return redirect('store:index')
        else:
            order_item[0].size = size
            order_item[0].color = color
            order.orderitems.add(order_item[0])
            return redirect('store:index')
    else:
        order = Order(user=request.user)
        order.save()
        order.orderitems.add(order_item[0])
        return redirect('store:index')


def cart_view(request):
    carts = Cart.objects.filter(user=request.user, purchased=False)
    orders = Order.objects.filter(user=request.user, ordered=False)
    if carts.exists() and orders.exists():
        order = orders[0]
        coupon_form = CouponCodeForm(request.POST)
        if coupon_form.is_valid():
            current_time = timezone.now()
            code = coupon_form.cleaned_data.get('code')
            coupon_obj = Coupon.objects.get(code=code, active=True)
            if coupon_obj.valid_to >= current_time:
                get_discount = (coupon_obj.discount / 100) * \
                    order.get_total_price()
                total_price_after_discount = order.get_total_price() - get_discount
                request.session['discount_total'] = total_price_after_discount
                request.session['coupon_code'] = code
                return redirect('order:cart')
        total_price_after_discount = request.session.get('discount_total')
        coupon_code = request.session.get('coupon_code')
        discount = order.get_total_price() - total_price_after_discount
        context = {
            'carts': carts,
            'order': order,
            'coupon_form': coupon_form,
            'coupon_code': coupon_code,
            'total_price_after_discount': total_price_after_discount,
            'discount': discount
        }
    return render(request, 'order/cart_view.html', context)


def remove_item_from_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    orders = Order.objects.filter(user=request.user, ordered=False)
    if orders.exists():
        order = orders[0]
        if order.orderitems.filter(item=item).exists():
            order_item = Cart.objects.filter(
                item=item, user=request.user, purchased=False)[0]
            order.orderitems.remove(order_item)
            order_item.delete()
            return redirect('order:cart')
        else:
            return redirect('order:cart')
    else:
        return redirect('order:cart')


def increase_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item = Cart.objects.filter(
                item=item, user=request.user, purchased=False)[0]
            if order_item.quantity >= 1:
                order_item.quantity += 1
                order_item.save()
                return redirect('order:cart')
        else:
            return redirect('store:index')
    else:
        return redirect('store:index')


def decrease_cart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item = Cart.objects.filter(
                item=item, user=request.user, purchased=False)[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
                return redirect("order:cart")
            else:
                order.orderitems.remove(order_item)
                order_item.delete()
                return redirect('store:index')
        else:
            return redirect('store:index')
    else:
        return redirect('store:index')

amader_dokan/templates/order/cart_view.html
{% extends 'base.html' %}
{% block index %}
<div class="container">
    <h1><a href="{% url 'store:index' %}">Home</a></h1>
</div>
<div class="display" style="display: flex;">

    <div class="con" style="background-color: aqua; width: 75%; display: lest; text-align: center;">
        <h1>Cart</h1>
        <table class="table" style="width: 100%;">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">image</th>
                    <th scope="col">Nmae</th>
                    <th scope="col">Color</th>
                    <th scope="col">Size</th>
                    <th scope="col">Price</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Total Price</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            {% if carts %}
            <tbody>
                {% for cart in carts %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td><img style="height: 100px; width: 100px;" src="{{ cart.item.image.url }}" alt=""></td>
                    <td>{{ cart.item.name }}</td>
                    {% if cart.color %}
                    <td>{{ cart.color }}</td>
                    {% else %}
                    <td>No Color</td>
                    {% endif %}
                    {% if cart.size %}
                    <td>{{ cart.size }}</td>
                    {% else %}
                    <td>No Size</td>
                    {% endif %}


                    <td>BDT
                        {% if cart.variation_single_price %}
                        {{ cart.variation_single_price }}
                        {% else %}
                        {{ cart.item.price }}
                        {% endif %}
                    </td>
                    <td>
                        <div class="quantity">
                            <a href="{% url 'order:decrease' pk=cart.item.pk %}"><i class="fa-solid fa-minus"></i></a>
                            <span> {{ cart.quantity }} </span>
                            <a href="{% url 'order:increase' pk=cart.item.pk %}"><i class="fa-solid fa-plus"></i></a>
                        </div>
                    </td>
                    <td>BDT
                        {% if cart.variation_total %}
                        {{ cart.variation_total }}
                        {% else %}
                        {{ cart.get_total }}
                        {% endif %}
                    </td>
                    <td><a href="{% url 'order:remove-item' pk=cart.item.pk %}"><button><i
                                    class="fa-solid fa-trash-can"></i></i></button></a></td>
                </tr>
                {% endfor %}
            </tbody>
            {% endif %}
        </table>
        <div class="coupon">
            <form action="" method="POST">
                {% csrf_token %}
                {{ coupon_form }}
                <button type="submit">Submit</i></button>
            </form>
            <br>
            <br>
        </div>
    </div>
    <div class="cont" style="background-color: rgb(51, 44, 83); width: 25%; display: lest; text-align: center;">
        <h1 style="color: aliceblue;">Cart Total</h1>
        <table class="table table-dark table-hover" style="width: 100%; padding: 0; margin: 0;">
            <tbody>
                <tr>
                    <th scope="row">Subtotal :</th>
                    <td colspan="2">BDT {{ order.get_total_price }}</td>
                </tr>
                <tr>
                    <th scope="row">Coupun Discount</th>
                    {% if discount %}
                    <td colspan="2">BDT - {{ discount }}</td>
                    {% else %}
                    <td colspan="2">0.00</td>
                    {% endif %}
                </tr>
                <tr>
                    <td colspan="2">Total</td>
                    <td>BDT
                        {% if total_price_after_discount %}
                        {{ total_price_after_discount }}
                        {% else %}
                        {{ order.get_total_price }}
                        {% endif %}
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

</div>
{% endblock %}